"""运行侧异常与稳定错误码定义。"""

from __future__ import annotations

from toolhive.core.exceptions import ToolHiveError

# ── 认证 ──
RUNTIME_AUTH_INVALID_SIGNATURE = "RUNTIME_AUTH_INVALID_SIGNATURE"
RUNTIME_AUTH_EXPIRED_TIMESTAMP = "RUNTIME_AUTH_EXPIRED_TIMESTAMP"
RUNTIME_AUTH_REPLAYED_NONCE = "RUNTIME_AUTH_REPLAYED_NONCE"
RUNTIME_AUTH_IP_NOT_ALLOWED = "RUNTIME_AUTH_IP_NOT_ALLOWED"
RUNTIME_AUTH_INVALID_SYSTEM = "RUNTIME_AUTH_INVALID_SYSTEM"
RUNTIME_AUTH_SECURITY_UNAVAILABLE = "RUNTIME_AUTH_SECURITY_UNAVAILABLE"
# ── 范围与调用控制 ──
RUNTIME_SCOPE_NOT_ALLOWED = "RUNTIME_SCOPE_NOT_ALLOWED"
RUNTIME_TOOL_NOT_FOUND = "RUNTIME_TOOL_NOT_FOUND"
RUNTIME_TOOL_NOT_AVAILABLE = "RUNTIME_TOOL_NOT_AVAILABLE"
RUNTIME_CONFIRMATION_REQUIRED = "RUNTIME_CONFIRMATION_REQUIRED"
RUNTIME_CONFIRMATION_INVALID = "RUNTIME_CONFIRMATION_INVALID"
# ── 流量与资源 ──
RUNTIME_RATE_LIMITED = "RUNTIME_RATE_LIMITED"
RUNTIME_CIRCUIT_OPEN = "RUNTIME_CIRCUIT_OPEN"
RUNTIME_REQUEST_TIMEOUT = "RUNTIME_REQUEST_TIMEOUT"
RUNTIME_IDEMPOTENCY_CONFLICT = "RUNTIME_IDEMPOTENCY_CONFLICT"
# ── Provider / 检索 / 通用 ──
RUNTIME_PROVIDER_ERROR = "RUNTIME_PROVIDER_ERROR"
RUNTIME_PROVIDER_TIMEOUT = "RUNTIME_PROVIDER_TIMEOUT"
RUNTIME_PROVIDER_SSRF_BLOCKED = "RUNTIME_PROVIDER_SSRF_BLOCKED"
RUNTIME_RETRIEVAL_UNAVAILABLE = "RUNTIME_RETRIEVAL_UNAVAILABLE"
RUNTIME_PARAMETER_INVALID = "RUNTIME_PARAMETER_INVALID"
RUNTIME_INTERNAL_ERROR = "RUNTIME_INTERNAL_ERROR"


class RuntimeApiError(ToolHiveError):
    """运行 API 业务错误：携带稳定错误码与 HTTP 状态。"""

    def __init__(self, code: str, message: str, http_status: int = 400):
        super().__init__(message)
        self.code = code
        self.message = message
        self.http_status = http_status
